name: Deploy Laravel Inertia

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ke Server Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/e_pengawalsekolah

            # 1. Reset dan tarik kod terkini
            git fetch --all
            git reset --hard origin/main
            git pull origin main

            # 2. Kemas kini pakej Backend
            composer install --no-dev --optimize-autoloader

            # 3. SET PERMISSION SEBELUM BUILD
            # Padam folder build lama menggunakan sudo supaya Vite ada kebenaran untuk buat baru
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S rm -rf public/build

            # 4. Masak fail UI Frontend
            npm install
            npm run build

            # 5. Cuci cache Laravel & Route
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # 6. SET PERMISSION SELEPAS BUILD
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S chown -R www-data:www-data public storage bootstrap/cache
            echo "${{ secrets.SERVER_PASSWORD }}" | sudo -S chmod -R 775 public storage bootstrap/cache